// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package apis

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersonalInformationList struct {
	Items                []*PersonalInformation `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PersonalInformationList) Reset()         { *m = PersonalInformationList{} }
func (m *PersonalInformationList) String() string { return proto.CompactTextString(m) }
func (*PersonalInformationList) ProtoMessage()    {}
func (*PersonalInformationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a6f99ca59053ac5f, []int{0}
}
func (m *PersonalInformationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalInformationList.Unmarshal(m, b)
}
func (m *PersonalInformationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalInformationList.Marshal(b, m, deterministic)
}
func (dst *PersonalInformationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalInformationList.Merge(dst, src)
}
func (m *PersonalInformationList) XXX_Size() int {
	return xxx_messageInfo_PersonalInformationList.Size(m)
}
func (m *PersonalInformationList) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalInformationList.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalInformationList proto.InternalMessageInfo

func (m *PersonalInformationList) GetItems() []*PersonalInformation {
	if m != nil {
		return m.Items
	}
	return nil
}

type PersonalInformation struct {
	// @gotags: gorm:"primaryKey;column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;column:id"`
	// @gotags: gorm:"column:name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"column:name"`
	// @gotags: gorm:"column:sex"
	Sex string `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty" gorm:"column:sex"`
	// @gotags: gorm:"column:tall"
	Tall float32 `protobuf:"fixed32,4,opt,name=tall,proto3" json:"tall,omitempty" gorm:"column:tall"`
	// @gotags: gorm:"column:weight"
	Weight float32 `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty" gorm:"column:weight"`
	// @gotags: gorm:"column:age"
	Age                  int64    `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty" gorm:"column:age"`
	// XXX_NoUnkeyedLiteral struct{} `json:"-"`
	// XXX_unrecognized     []byte   `json:"-"`
	// XXX_sizecache        int32    `json:"-"`
}

func (m *PersonalInformation) Reset()         { *m = PersonalInformation{} }
func (m *PersonalInformation) String() string { return proto.CompactTextString(m) }
func (*PersonalInformation) ProtoMessage()    {}
func (*PersonalInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_a6f99ca59053ac5f, []int{1}
}
func (m *PersonalInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalInformation.Unmarshal(m, b)
}
func (m *PersonalInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalInformation.Marshal(b, m, deterministic)
}
func (dst *PersonalInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalInformation.Merge(dst, src)
}
func (m *PersonalInformation) XXX_Size() int {
	return xxx_messageInfo_PersonalInformation.Size(m)
}
func (m *PersonalInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalInformation proto.InternalMessageInfo

func (m *PersonalInformation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PersonalInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonalInformation) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *PersonalInformation) GetTall() float32 {
	if m != nil {
		return m.Tall
	}
	return 0
}

func (m *PersonalInformation) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PersonalInformation) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*PersonalInformationList)(nil), "apis.PersonalInformationList")
	proto.RegisterType((*PersonalInformation)(nil), "apis.PersonalInformation")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_a6f99ca59053ac5f) }

var fileDescriptor_types_a6f99ca59053ac5f = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0xaa, 0xc2, 0x30,
	0x10, 0x86, 0x49, 0xd2, 0x16, 0xde, 0x14, 0x1e, 0x8f, 0x3c, 0xd0, 0xb8, 0x0b, 0x5d, 0x65, 0x55,
	0x41, 0x4f, 0xa1, 0xb8, 0x90, 0xdc, 0x20, 0xd2, 0x58, 0x03, 0x6d, 0x52, 0x9a, 0x01, 0xf5, 0x08,
	0xde, 0x5a, 0x12, 0x5d, 0x76, 0xf7, 0xcd, 0x3f, 0xdf, 0xcf, 0x30, 0x50, 0xe3, 0x73, 0xb2, 0xb1,
	0x9d, 0xe6, 0x80, 0x81, 0x17, 0x66, 0x72, 0xb1, 0x39, 0xc2, 0xfa, 0x6c, 0xe7, 0x18, 0xbc, 0x19,
	0x0e, 0xfe, 0x1a, 0xe6, 0xd1, 0xa0, 0x0b, 0xfe, 0xe4, 0x22, 0xf2, 0x2d, 0x94, 0x0e, 0xed, 0x18,
	0x05, 0x91, 0x4c, 0xd5, 0xbb, 0x4d, 0x9b, 0x0a, 0xed, 0x82, 0xad, 0x3f, 0x5e, 0xf3, 0x22, 0xf0,
	0xbf, 0xb0, 0xe6, 0xbf, 0x40, 0x5d, 0x27, 0x88, 0x24, 0x8a, 0x69, 0xea, 0x3a, 0xce, 0xa1, 0xf0,
	0x66, 0xb4, 0x82, 0x4a, 0xa2, 0x7e, 0x74, 0x66, 0xfe, 0x07, 0x2c, 0xda, 0x87, 0x60, 0x39, 0x4a,
	0x98, 0x2c, 0x34, 0xc3, 0x20, 0x0a, 0x49, 0x14, 0xd5, 0x99, 0xf9, 0x0a, 0xaa, 0xbb, 0x75, 0xfd,
	0x0d, 0x45, 0x99, 0xd3, 0xef, 0x94, 0xda, 0xa6, 0xb7, 0xa2, 0xca, 0x27, 0x12, 0x5e, 0xaa, 0xfc,
	0xe4, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x4b, 0xca, 0x00, 0xf3, 0x00, 0x00, 0x00,
}
