// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package apis

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersonalInformationList struct {
	Items                []*PersonalInformation `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PersonalInformationList) Reset()         { *m = PersonalInformationList{} }
func (m *PersonalInformationList) String() string { return proto.CompactTextString(m) }
func (*PersonalInformationList) ProtoMessage()    {}
func (*PersonalInformationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_351f8e76872967c8, []int{0}
}
func (m *PersonalInformationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalInformationList.Unmarshal(m, b)
}
func (m *PersonalInformationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalInformationList.Marshal(b, m, deterministic)
}
func (dst *PersonalInformationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalInformationList.Merge(dst, src)
}
func (m *PersonalInformationList) XXX_Size() int {
	return xxx_messageInfo_PersonalInformationList.Size(m)
}
func (m *PersonalInformationList) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalInformationList.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalInformationList proto.InternalMessageInfo

func (m *PersonalInformationList) GetItems() []*PersonalInformation {
	if m != nil {
		return m.Items
	}
	return nil
}

type PersonalInformation struct {
	// @gotags: gorm:"primaryKey;column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: gorm:"column:name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: gorm:"column:sex"
	Sex string `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	// @gotags: gorm:"column:tall"
	Tall float32 `protobuf:"fixed32,4,opt,name=tall,proto3" json:"tall,omitempty"`
	// @gotags: gorm:"column:weight"
	Weight float32 `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	// @gotags: gorm:"column:age"
	Age                  int64    `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonalInformation) Reset()         { *m = PersonalInformation{} }
func (m *PersonalInformation) String() string { return proto.CompactTextString(m) }
func (*PersonalInformation) ProtoMessage()    {}
func (*PersonalInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_351f8e76872967c8, []int{1}
}
func (m *PersonalInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalInformation.Unmarshal(m, b)
}
func (m *PersonalInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalInformation.Marshal(b, m, deterministic)
}
func (dst *PersonalInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalInformation.Merge(dst, src)
}
func (m *PersonalInformation) XXX_Size() int {
	return xxx_messageInfo_PersonalInformation.Size(m)
}
func (m *PersonalInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalInformation proto.InternalMessageInfo

func (m *PersonalInformation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PersonalInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonalInformation) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *PersonalInformation) GetTall() float32 {
	if m != nil {
		return m.Tall
	}
	return 0
}

func (m *PersonalInformation) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PersonalInformation) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*PersonalInformationList)(nil), "apis.PersonalInformationList")
	proto.RegisterType((*PersonalInformation)(nil), "apis.PersonalInformation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RankServiceClient is the client API for RankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankServiceClient interface {
	Register(ctx context.Context, in *PersonalInformation, opts ...grpc.CallOption) (*PersonalInformation, error)
}

type rankServiceClient struct {
	cc *grpc.ClientConn
}

func NewRankServiceClient(cc *grpc.ClientConn) RankServiceClient {
	return &rankServiceClient{cc}
}

func (c *rankServiceClient) Register(ctx context.Context, in *PersonalInformation, opts ...grpc.CallOption) (*PersonalInformation, error) {
	out := new(PersonalInformation)
	err := c.cc.Invoke(ctx, "/apis.RankService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankServiceServer is the server API for RankService service.
type RankServiceServer interface {
	Register(context.Context, *PersonalInformation) (*PersonalInformation, error)
}

func RegisterRankServiceServer(s *grpc.Server, srv RankServiceServer) {
	s.RegisterService(&_RankService_serviceDesc, srv)
}

func _RankService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonalInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.RankService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankServiceServer).Register(ctx, req.(*PersonalInformation))
	}
	return interceptor(ctx, in, info, handler)
}

var _RankService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apis.RankService",
	HandlerType: (*RankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RankService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_351f8e76872967c8) }

var fileDescriptor_types_351f8e76872967c8 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4d, 0x4a, 0xc5, 0x30,
	0x10, 0xc7, 0x4d, 0xdb, 0x57, 0x74, 0x0a, 0x22, 0x23, 0x68, 0x74, 0x55, 0xba, 0xea, 0xaa, 0xc2,
	0xf3, 0x06, 0xee, 0x14, 0x17, 0x1a, 0x4f, 0x10, 0x7d, 0x63, 0x1d, 0x6c, 0x93, 0x92, 0x0c, 0x7e,
	0x1c, 0xc1, 0x5b, 0x4b, 0xa2, 0xcb, 0xd7, 0xdd, 0x6f, 0xfe, 0x1f, 0x0c, 0x33, 0xd0, 0xc8, 0xf7,
	0x42, 0x71, 0x58, 0x82, 0x17, 0x8f, 0x95, 0x5d, 0x38, 0x76, 0x77, 0x70, 0xfe, 0x40, 0x21, 0x7a,
	0x67, 0xa7, 0x5b, 0xf7, 0xea, 0xc3, 0x6c, 0x85, 0xbd, 0xbb, 0xe7, 0x28, 0x78, 0x05, 0x1b, 0x16,
	0x9a, 0xa3, 0x56, 0x6d, 0xd9, 0x37, 0xdb, 0x8b, 0x21, 0x15, 0x86, 0x3d, 0x69, 0xf3, 0x97, 0xeb,
	0x7e, 0x14, 0x9c, 0xee, 0xb1, 0xf1, 0x18, 0x0a, 0xde, 0x69, 0xd5, 0xaa, 0xbe, 0x34, 0x05, 0xef,
	0x10, 0xa1, 0x72, 0x76, 0x26, 0x5d, 0xb4, 0xaa, 0x3f, 0x32, 0x99, 0xf1, 0x04, 0xca, 0x48, 0x5f,
	0xba, 0xcc, 0x52, 0xc2, 0x94, 0x12, 0x3b, 0x4d, 0xba, 0x6a, 0x55, 0x5f, 0x98, 0xcc, 0x78, 0x06,
	0xf5, 0x27, 0xf1, 0xf8, 0x26, 0x7a, 0x93, 0xd5, 0xff, 0x29, 0xb5, 0xed, 0x48, 0xba, 0xce, 0x2b,
	0x12, 0x6e, 0x1f, 0xa1, 0x31, 0xd6, 0xbd, 0x3f, 0x51, 0xf8, 0xe0, 0x17, 0xc2, 0x1b, 0x38, 0x34,
	0x34, 0x72, 0x14, 0x0a, 0xb8, 0x7e, 0xc8, 0xe5, 0xba, 0xd5, 0x1d, 0x3c, 0xd7, 0xf9, 0x6f, 0xd7,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0xac, 0x6c, 0xe5, 0x46, 0x01, 0x00, 0x00,
}
